baseURL = "https://CyberRiskQuant.com/"
languageCode = "en-us"
title = "Cyber Risk Quant"
theme = "hugo-paradigm"
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"

[outputFormats]
 [outputFormats.html]
   mediaType = "text/html"
   
 [outputFormats.rss]
   mediaType = "application/rss+xml"
   baseName = "rss"

 [outputs]
    posts = ["html", "rss"]
    pages = ["html"]
    home = ["html", "rss"]
    section = ["html"]
    taxonomy = ["html"]
    term = ["html"]
     
[Author]
    name = "Duncan Hart"
    email = "DAH@CyberRiskQuant.com"

[Params]
    paginate = 3
    inLanguage = "en-US"
    
[Permalink]
    post = "/:year/:month/:title/"
    
[taxonomies]
    tag = "tags"
    category = "categories"
    work =  "works"
    author = "authors"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5


 
# Main Menu
[[menu.main]]
    name = "Contact us"
    url = "/contact/"
    weight = 2 
[[menu.main]]
    name = "About us"
    url = "/about/"
    weight = 3
# Footer Menu Primary
[[menu.footer_primary]]
	name = "Home"
	url = "/"
    weight = 1
[[menu.footer_primary]]
    name = "Sitemap"
    url = "sitemap.xml"
    weight = 2
[[menu.footer_primary]]
    name = "Imprint"
    url = "/imprint/"
    weight = 3
[[menu.footer_primary]]
    name = "Policies"
    url = "/policies/"
    weight = 4
# Footer Menu Secondary
[[menu.footer_secondary]]
    name = "5/171 Collins Street, Melbourne, VIC 3000, Australia"
    url = "https://g.page/CyberRiskQuant?share"
    weight = 1
[[menu.footer_secondary]]
    name = "+61 3 7020 3350"
    url = "tel:+6137020350"
    weight = 2 
[[menu.footer_secondary]]
    name = "HereToHelp@CyberRiskQuant.com"
    url = "mailto:HereToHelp@CyberRiskQuant.com"
    weight = 3
